plugins:
  extractors:
  - name: tap-postgres--region
    inherit_from: tap-postgres
    select:
    - public-region.*
  loaders:
  - name: target-postgres--region
    inherit_from: target-postgres

jobs:
- name: region-pipeline
  tasks:
  - tap-postgres--region target-postgres--region