plugins:
  extractors:
  - name: tap-postgres--employees
    inherit_from: tap-postgres
    select:
    - public-employees.*
  loaders:
  - name: target-postgres--employees
    inherit_from: target-postgres

jobs:
- name: employees-pipeline
  tasks:
  - tap-postgres--employees target-postgres--employees