plugins:
  extractors:
  - name: tap-postgres--customer_demographics
    inherit_from: tap-postgres
    select:
    - public-customer_demographics.*
  loaders:
  - name: target-postgres--customer_demographics
    inherit_from: target-postgres

jobs:
- name: customer_demographics-pipeline
  tasks:
  - tap-postgres--customer_demographics target-postgres--customer_demographics