plugins:
  extractors:
  - name: tap-postgres--order_details
    inherit_from: tap-postgres
    select:
    - public-order_details.*
  loaders:
  - name: target-postgres--order_details
    inherit_from: target-postgres

jobs:
- name: order_details-pipeline
  tasks:
  - tap-postgres--order_details target-postgres--order_details