plugins:
  extractors:
  - name: tap-postgres--entire
    inherit_from: tap-postgres
    config:
      port: 5432
    select: []
  loaders:
  - name: target-postgres--entire
    inherit_from: target-postgres
    config:
      port: 5433

jobs:
- name: entire-pipeline
  tasks:
  - tap-postgres--entire target-postgres--entire
