plugins:
  extractors:
  - name: tap-postgres--products
    inherit_from: tap-postgres
    select:
    - public-products.*
  loaders:
  - name: target-postgres--products
    inherit_from: target-postgres

jobs:
- name: products-pipeline
  tasks:
  - tap-postgres--products target-postgres--products