plugins:
  extractors:
  - name: tap-postgres--suppliers
    inherit_from: tap-postgres
    select:
    - public-suppliers.*
  loaders:
  - name: target-postgres--suppliers
    inherit_from: target-postgres

jobs:
- name: suppliers-pipeline
  tasks:
  - tap-postgres--suppliers target-postgres--suppliers