plugins:
  extractors:
  - name: tap-postgres--customer_customer_demo
    inherit_from: tap-postgres
    select:
    - public-customer_customer_demo.*
  loaders:
  - name: target-postgres--customer_customer_demo
    inherit_from: target-postgres

jobs:
- name: customer_customer_demo-pipeline
  tasks:
  - tap-postgres--customer_customer_demo target-postgres--customer_customer_demo