plugins:
  extractors:
  - name: tap-postgres--territories
    inherit_from: tap-postgres
    select:
    - public-territories.*
  loaders:
  - name: target-postgres--territories
    inherit_from: target-postgres

jobs:
- name: territories-pipeline
  tasks:
  - tap-postgres--territories target-postgres--territories